# Use an official Node.js image as the base
FROM node:18.17.0

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend code
COPY . .

# Expose the default Strapi port
EXPOSE 1337

# Start the Strapi server
CMD ["npm", "run", "develop"]
